<?php

namespace App\Enum;

enum ExchangeRatesNameWithCodeEnum: string
{
    case USD = '840';
    case EUR = '978';
    case GBP = '826';
    case JPY = '392';
    case CHF = '756';
    case CNY = '156';
    case AED = '784';
    case AFN = '971';
    case ALL = '8';
    case AMD = '51';
    case AOA = '973';
    case ARS = '32';
    case AUD = '36';
    case AZN = '944';
    case BDT = '50';
    case BGN = '975';
    case BHD = '48';
    case BIF = '108';
    case BND = '96';
    case BOB = '68';
    case BRL = '986';
    case BWP = '72';
    case BYN = '933';
    case CAD = '124';
    case CDF = '976';
    case CLP = '152';
    case COP = '170';
    case CRC = '188';
    case CUP = '192';
    case CZK = '203';
    case DJF = '262';
    case DKK = '208';
    case DZD = '12';
    case EGP = '818';
    case ETB = '230';
    case GEL = '981';
    case GHS = '936';
    case GMD = '270';
    case GNF = '324';
    case HKD = '344';
    case HRK = '191';
    case HUF = '348';
    case IDR = '360';
    case ILS = '376';
    case INR = '356';
    case IQD = '368';
    case IRR = '364';
    case ISK = '352';
    case JOD = '400';
    case KES = '404';
    case KGS = '417';
    case KHR = '116';
    case KPW = '408';
    case KRW = '410';
    case KWD = '414';
    case KZT = '398';
    case LAK = '418';
    case LBP = '422';
    case LKR = '144';
    case LYD = '434';
    case MAD = '504';
    case MDL = '498';
    case MGA = '969';
    case MKD = '807';
    case MNT = '496';
    case MRO = '478';
    case MUR = '480';
    case MVR = '462';
    case MWK = '454';
    case MXN = '484';
    case MYR = '458';
    case MZN = '943';
    case NAD = '516';
    case NGN = '566';
    case NIO = '558';
    case NOK = '578';
    case NPR = '524';
    case NZD = '554';
    case OMR = '512';
    case PEN = '604';
    case PHP = '608';
    case PKR = '586';
    case PLN = '985';
    case PYG = '600';
    case QAR = '634';
    case RON = '946';
    case RSD = '941';
    case SAR = '682';
    case SCR = '690';
    case SDG = '938';
    case SEK = '752';
    case SGD = '702';
    case SLL = '694';
    case SOS = '706';
    case SRD = '968';
    case SYP = '760';
    case SZL = '748';
    case THB = '764';
    case TJS = '972';
    case TMT = '795';
    case TND = '788';
    case TRY = '949';
    case TWD = '901';
    case TZS = '834';
    case UGX = '800';
    case UYU = '858';
    case UZS = '860';
    case VEF = '937';
    case VND = '704';
    case XAF = '950';
    case XDR = '960';
    case XOF = '952';
    case YER = '886';
    case ZAR = '710';
    case ZMK = '894';

    static function toArray(): array
    {
        return [
            self::AED->value => self::AED->name,
            self::AFN->value => self::AED->name,
            self::ALL->value => self::ALL->name,
            self::AMD->value => self::AMD->name,
            self::AOA->value => self::AOA->name,
            self::ARS->value => self::ARS->name,
            self::AUD->value => self::AUD->name,
            self::AZN->value => self::AZN->name,
            self::BDT->value => self::BDT->name,
            self::BHD->value => self::BHD->name,
            self::BGN->value => self::BGN->name,
            self::BIF->value => self::BIF->name,
            self::BOB->value => self::BOB->name,
            self::BRL->value => self::BRL->name,
            self::BND->value => self::BND->name,
            self::BWP->value => self::BWP->name,
            self::BYN->value => self::BYN->name,
            self::CAD->value => self::CAD->name,
            self::CDF->value => self::CDF->name,
            self::CHF->value => self::CHF->name,
            self::CLP->value => self::CLP->name,
            self::CNY->value => self::CNY->name,
            self::COP->value => self::COP->name,
            self::CRC->value => self::CRC->name,
            self::CUP->value => self::CUP->name,
            self::CZK->value => self::CZK->name,
            self::DJF->value => self::DJF->name,
            self::DKK->value => self::DKK->name,
            self::DZD->value => self::DZD->name,
            self::EGP->value => self::EGP->name,
            self::ETB->value => self::ETB->name,
            self::EUR->value => self::EUR->name,
            self::GBP->value => self::GBP->name,
            self::GEL->value => self::GEL->name,
            self::GHS->value => self::GHS->name,
            self::GMD->value => self::GMD->name,
            self::GNF->value => self::GNF->name,
            self::HKD->value => self::HKD->name,
            self::HRK->value => self::HRK->name,
            self::HUF->value => self::HUF->name,
            self::IDR->value => self::IDR->name,
            self::ILS->value => self::ILS->name,
            self::INR->value => self::INR->name,
            self::IQD->value => self::IQD->name,
            self::IRR->value => self::IRR->name,
            self::ISK->value => self::ISK->name,
            self::JOD->value => self::JOD->name,
            self::JPY->value => self::JPY->name,
            self::KES->value => self::KES->name,
            self::KGS->value => self::KGS->name,
            self::KHR->value => self::KHR->name,
            self::KPW->value => self::KPW->name,
            self::KRW->value => self::KRW->name,
            self::KWD->value => self::KWD->name,
            self::KZT->value => self::KZT->name,
            self::LAK->value => self::LAK->name,
            self::LBP->value => self::LBP->name,
            self::LKR->value => self::LKR->name,
            self::LYD->value => self::LYD->name,
            self::MAD->value => self::MAD->name,
            self::MDL->value => self::MDL->name,
            self::MGA->value => self::MGA->name,
            self::MKD->value => self::MKD->name,
            self::MNT->value => self::MNT->name,
            self::MRO->value => self::MRO->name,
            self::MUR->value => self::MUR->name,
            self::MVR->value => self::MVR->name,
            self::MWK->value => self::MWK->name,
            self::MXN->value => self::MXN->name,
            self::MYR->value => self::MYR->name,
            self::MZN->value => self::MZN->name,
            self::NAD->value => self::NAD->name,
            self::NGN->value => self::NGN->name,
            self::NIO->value => self::NIO->name,
            self::NOK->value => self::NOK->name,
            self::NPR->value => self::NPR->name,
            self::NZD->value => self::NZD->name,
            self::OMR->value => self::OMR->name,
            self::PEN->value => self::PEN->name,
            self::PHP->value => self::PHP->name,
            self::PKR->value => self::PKR->name,
            self::PLN->value => self::PLN->name,
            self::PYG->value => self::PYG->name,
            self::QAR->value => self::QAR->name,
            self::RON->value => self::RON->name,
            self::RSD->value => self::RSD->name,
            self::SAR->value => self::SAR->name,
            self::SCR->value => self::SCR->name,
            self::SDG->value => self::SDG->name,
            self::SEK->value => self::SEK->name,
            self::SLL->value => self::SLL->name,
            self::SOS->value => self::SOS->name,
            self::SRD->value => self::SRD->name,
            self::SYP->value => self::SYP->name,
            self::SZL->value => self::SZL->name,
            self::SGD->value => self::SGD->name,
            self::THB->value => self::THB->name,
            self::TJS->value => self::TJS->name,
            self::TMT->value => self::TMT->name,
            self::TND->value => self::TND->name,
            self::TRY->value => self::TRY->name,
            self::TWD->value => self::TWD->name,
            self::TZS->value => self::TZS->name,
            self::UGX->value => self::UGX->name,
            self::USD->value => self::USD->name,
            self::UYU->value => self::UYU->name,
            self::UZS->value => self::UZS->name,
            self::VEF->value => self::VEF->name,
            self::VND->value => self::VND->name,
            self::XAF->value => self::XAF->name,
            self::XDR->value => self::XDR->name,
            self::XOF->value => self::XOF->name,
            self::YER->value => self::YER->name,
            self::ZAR->value => self::ZAR->name,
            self::ZMK->value => self::ZMK->name,
        ];
    }
}
